services:
  yoteams:
    image: yoteams
    build:
      context: .
      dockerfile: YoTeams/Dockerfile

  yoteamservices:
    image: yoteamservices
    build:
      context: .
      dockerfile: YoTeamServices/Dockerfile
